movie_main.o: include/linked_list.hpp 
	g++ -pedantic -Wall -Werror -Wformat=2 -std=c++11 -o build/linked_list_test tests/linked_list_test.cpp -I /usr/include/gtest/ -L /usr/lib/ -lgtest -lgtest_main -lpthread
